version: 2
jobs:

  test:
    working_directory: ~/click-to-congress
    docker:
      - image: circleci/node:8.10-stretch
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/click-to-congress/node_modules ]]; then
              npm install
              npm install mocha
            fi
      - run:
          name: Test
          command: |
            npm test
      - save_cache:
          key: npm-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/click-to-congress/node_modules

  deploy:
    working_directory: ~/click-to-congress
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deploy-{{ checksum "circle.yml" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python3 -m venv ~/.venv
              source ~/.venv/bin/activate
              pip3 install -U git+https://github.com/nypublicradio/nyprsetuptools.git
            fi
      - deploy:
          command: |
            source ~/.venv/bin/activate
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              nyprsetuptools DockerDeploy --environment=demo \
                                          --ecs-cluster=microservices \
                                          --ecr-repository=click-to-congress \
                                          --test='npm test' \
                                          --tag=demo \
                                          --wait=300
            elif echo "$CIRCLE_TAG" | grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
              nyprsetuptools DockerDeploy --environment=prod \
                                          --ecs-cluster=microservices \
                                          --ecr-repository=click-to-congress \
                                          --test='npm test' \
                                          --tag="$CIRCLE_TAG" \
                                          --wait=300
            fi
      - save_cache:
          key: deploy-{{ checksum "circle.yml" }}
          paths:
            - ~/.venv
            - ~/click-to-congress/.eggs

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master

experimental:
  notify:
    branches:
      only:
        - master
